1. Implement a K-Nearest Neighbors (KNN) classifier in Python to predict whether a Flipkart product review is 'positive' or 'negative' using a small dataset of review texts and their labels.<br><br><em><strong>Hint:</strong> Use scikit-learn's KNeighborsClassifier and convert the text data into numerical features using CountVectorizer.</em>


In [1]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score

# Load Dataset
df = pd.read_csv("flipkart_reviews.csv")

print(df)

# Features
X = df["Review"]

# Labels
y = df["Sentiment"]

# Convert text into numbers
vectorizer = CountVectorizer()

X = vectorizer.fit_transform(X)

# Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

# Create Model
model = KNeighborsClassifier(n_neighbors=3)

# Train Model
model.fit(X_train, y_train)

# Prediction
prediction = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, prediction)

print("\nPrediction")
print(prediction)

print("\nAccuracy =", accuracy)

                Review Sentiment
0    Excellent product  Positive
1    Very good quality  Positive
2        Amazing phone  Positive
3      Loved this item  Positive
4         Worth buying  Positive
5          Bad quality  Negative
6       Waste of money  Negative
7    Very poor product  Negative
8        Not satisfied  Negative
9  Terrible experience  Negative

Prediction
['Positive' 'Positive' 'Positive']

Accuracy = 0.3333333333333333


2. Compare the accuracy of KNN using Euclidean distance vs. Manhattan distance on a dataset of Spotify song features (e.g., tempo, danceability, energy) to classify songs as 'workout' or 'chill' playlists.<br><br><em><strong>Hint:</strong> Use the 'metric' parameter in KNeighborsClassifier to switch between 'euclidean' and 'manhattan'.</em>

In [4]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Load Dataset
df = pd.read_csv("spottify_songs.csv")

print("Dataset")
print(df)

# Features
X = df[["tempo", "danceability", "energy"]]

# Target
y = df["playlist"]

# Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

# ------------------------------
# Euclidean Distance
# ------------------------------
knn_euclidean = KNeighborsClassifier(
    n_neighbors=3,
    metric="euclidean"
)

knn_euclidean.fit(X_train, y_train)

pred1 = knn_euclidean.predict(X_test)

acc1 = accuracy_score(y_test, pred1)

print("\nEuclidean Accuracy =", acc1)

# ------------------------------
# Manhattan Distance
# ------------------------------
knn_manhattan = KNeighborsClassifier(
    n_neighbors=3,
    metric="manhattan"
)

knn_manhattan.fit(X_train, y_train)

pred2 = knn_manhattan.predict(X_test)

acc2 = accuracy_score(y_test, pred2)

print("Manhattan Accuracy =", acc2)

Dataset
   tempo  danceability  energy playlist
0    120          0.80    0.90  Workout
1    115          0.75    0.85  Workout
2    130          0.90    0.95  Workout
3    125          0.85    0.88  Workout
4    128          0.82    0.92  Workout
5     90          0.45    0.40    Chill
6     85          0.40    0.35    Chill
7     95          0.50    0.45    Chill
8     88          0.42    0.38    Chill
9     92          0.48    0.42    Chill

Euclidean Accuracy = 1.0
Manhattan Accuracy = 1.0


3. Use Gaussian Naive Bayes to classify whether an IRCTC train booking is likely to be 'confirmed' or 'waitlisted' based on features like booking time, train popularity, and travel day (use a small mock dataset).

In [5]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix

# Load Dataset
df = pd.read_csv("irctc_booking.csv")

print("Dataset")
print(df)

# Features
X = df[["booking_time", "train_popularity", "travel_day"]]

# Target
y = df["status"]

# Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

# Create Model
model = GaussianNB()

# Train Model
model.fit(X_train, y_train)

# Prediction
prediction = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, prediction)

print("\nPredicted Values")
print(prediction)

print("\nActual Values")
print(y_test.values)

print("\nAccuracy =", accuracy)

print("\nConfusion Matrix")
print(confusion_matrix(y_test, prediction))

Dataset
   booking_time  train_popularity  travel_day      status
0             8                90           1   Confirmed
1            10                85           2   Confirmed
2            12                70           5  Waitlisted
3            15                60           6  Waitlisted
4             9                95           1   Confirmed
5            14                65           7  Waitlisted
6            11                80           3   Confirmed
7            16                55           6  Waitlisted
8            13                75           4   Confirmed
9            17                50           7  Waitlisted

Predicted Values
['Waitlisted' 'Confirmed' 'Waitlisted']

Actual Values
['Confirmed' 'Confirmed' 'Waitlisted']

Accuracy = 0.6666666666666666

Confusion Matrix
[[1 1]
 [0 1]]


4. Build a Multinomial Naive Bayes classifier to categorize WhatsApp chat messages as 'personal', 'group', or 'spam' using example message texts and labels.<br><br><em><strong>Constraint:</strong> Use scikit-learn's MultinomialNB and show the confusion matrix for your results.</em>

In [9]:
import pandas as pd

from sklearn.model_selection import train_test_split

from sklearn.feature_extraction.text import CountVectorizer

from sklearn.naive_bayes import MultinomialNB

from sklearn.metrics import accuracy_score, confusion_matrix

# Load Dataset
df = pd.read_csv("whatsapp_messages.csv")

print("Dataset")
print(df)

# Features
X = df["Message"]

# Target
y = df["Category"]

# Convert text into numbers
vectorizer = CountVectorizer()

X = vectorizer.fit_transform(X)

# Split Dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    train_size=0.7,
    test_size=0.3,
    random_state=42
)

# Create Model
model = MultinomialNB()

# Train Model
model.fit(X_train, y_train)

# Prediction
prediction = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, prediction)

print("\nPredicted Labels")
print(prediction)

print("\nActual Labels")
print(y_test.values)

print("\nAccuracy =", accuracy)

print("\nConfusion Matrix")

cm = confusion_matrix(y_test, prediction)

print(cm)

Dataset
                                          Message  Category
Hi                                   how are you?  Personal
Let's meet tomorrow                      Personal       NaN
Happy Birthday!                          Personal       NaN
Call me when you are free                Personal       NaN
Meeting at 5 PM today                       Group       NaN
Project discussion at 7 PM                  Group       NaN
Please submit your assignment               Group       NaN
Team meeting tomorrow morning               Group       NaN
Congratulations! You won a lottery           Spam       NaN
Click here to claim your prize               Spam       NaN
Earn money from home                         Spam       NaN
Limited offer! Buy now                       Spam       NaN


ValueError: Input contains NaN

5. Use ChatGPT or Copilot to generate Python code for a KNN-based image classifier that distinguishes between images of cricket bats and footballs (use any small sample image dataset or random pixel arrays), then run and test the code, noting any changes you made to get it working.<br><br><em><strong>Hint:</strong> Paste the AI-generated code, describe any errors, and how you fixed them.</em>
Topic Repository URL

In [7]:
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score

# Random seed
np.random.seed(42)

# Create 20 random images (8x8 pixels)

X = np.random.randint(0, 256, size=(20, 64))

# Labels
# 0 = Cricket Bat
# 1 = Football

y = np.array([
    0,0,0,0,0,
    0,0,0,0,0,
    1,1,1,1,1,
    1,1,1,1,1
])

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42
)

# KNN Model
model = KNeighborsClassifier(n_neighbors=3)

# Train Model
model.fit(X_train, y_train)

# Prediction
prediction = model.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, prediction)

print("Actual Labels")
print(y_test)

print("\nPredicted Labels")
print(prediction)

print("\nAccuracy =", accuracy)

Actual Labels
[0 1 1 0 0 0]

Predicted Labels
[0 1 0 0 1 0]

Accuracy = 0.6666666666666666
