1. Create a 5x5 NumPy matrix with random integers from 0 to 9, then define a 3x3 filter (kernel) and manually perform a single convolution operation (no padding, stride 1) to produce the activation map.

In [1]:
import numpy as np

# Create 5x5 input matrix
input_matrix = np.random.randint(0, 10, (5, 5))

print("Input Matrix:")
print(input_matrix)

# 3x3 Kernel
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

print("\nKernel:")
print(kernel)

# Output Activation Map (3x3)
output = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        region = input_matrix[i:i+3, j:j+3]
        output[i, j] = np.sum(region * kernel)

print("\nActivation Map:")
print(output)

Input Matrix:
[[8 7 3 5 8]
 [9 8 9 1 1]
 [1 2 6 5 0]
 [7 8 4 8 3]
 [8 1 2 7 3]]

Kernel:
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]

Activation Map:
[[ 0.  6.  9.]
 [-2.  4. 15.]
 [ 4. -9.  6.]]


2. Implement a Python function apply_stride_convolution(input_matrix, kernel, stride) that performs convolution with a given stride on a 6x6 matrix and a 3x3 kernel, returning the resulting activation map.<br><br><em><strong>Hint:</strong> Use nested loops to move the kernel by the stride value over the input matrix.</em>

In [2]:
import numpy as np

def apply_stride_convolution(input_matrix, kernel, stride):

    n = input_matrix.shape[0]
    k = kernel.shape[0]

    output_size = ((n - k) // stride) + 1

    output = np.zeros((output_size, output_size))

    for i in range(0, n-k+1, stride):
        for j in range(0, n-k+1, stride):

            region = input_matrix[i:i+k, j:j+k]

            output[i//stride, j//stride] = np.sum(region * kernel)

    return output


# Example
matrix = np.random.randint(0, 10, (6,6))

kernel = np.array([
    [1,0,-1],
    [1,0,-1],
    [1,0,-1]
])

result = apply_stride_convolution(matrix, kernel, stride=2)

print(result)

[[-13.   3.]
 [ -7.  12.]]


3. Modify your convolution code to add zero-padding of 1 around the input matrix before applying the convolution, and show the new activation map output.

In [3]:
import numpy as np

# Original Matrix
matrix = np.random.randint(0,10,(5,5))

# Add Zero Padding
padded = np.pad(
    matrix,
    pad_width=1,
    mode='constant',
    constant_values=0
)

kernel = np.array([
    [1,0,-1],
    [1,0,-1],
    [1,0,-1]
])

output = np.zeros((5,5))

for i in range(5):
    for j in range(5):

        region = padded[i:i+3, j:j+3]

        output[i,j] = np.sum(region * kernel)

print("Original Matrix:")
print(matrix)

print("\nPadded Matrix:")
print(padded)

print("\nActivation Map:")
print(output)

Original Matrix:
[[9 4 4 7 3]
 [8 4 1 1 1]
 [9 1 4 6 1]
 [4 8 2 4 7]
 [4 8 6 7 7]]

Padded Matrix:
[[0 0 0 0 0 0 0]
 [0 9 4 4 7 3 0]
 [0 8 4 1 1 1 0]
 [0 9 1 4 6 1 0]
 [0 4 8 2 4 7 0]
 [0 4 8 6 7 7 0]
 [0 0 0 0 0 0 0]]

Activation Map:
[[ -8.  12.   0.   1.   8.]
 [ -9.  17.  -5.   4.  14.]
 [-13.  14.   2.  -2.  11.]
 [-17.   5.   0.  -3.  17.]
 [-16.   0.   5.  -6.  11.]]


4. Visualize the effect of different filters by applying both an edge detection kernel and a blur kernel to the same 5x5 matrix and print both activation maps side by side.<br><br><em><strong>Hint:</strong> Use the Sobel or Laplacian kernel for edge detection and an averaging kernel for blur.</em>

In [4]:
import numpy as np

matrix = np.random.randint(0,10,(5,5))

# Edge Detection Kernel (Sobel-like)
edge_kernel = np.array([
    [1,0,-1],
    [2,0,-2],
    [1,0,-1]
])

# Blur Kernel
blur_kernel = np.ones((3,3)) / 9

def convolution(matrix, kernel):

    output = np.zeros((3,3))

    for i in range(3):
        for j in range(3):

            region = matrix[i:i+3,j:j+3]

            output[i,j] = np.sum(region * kernel)

    return output

edge_output = convolution(matrix, edge_kernel)

blur_output = convolution(matrix, blur_kernel)

print("Input Matrix:")
print(matrix)

print("\nEdge Detection Output:")
print(edge_output)

print("\nBlur Output:")
print(blur_output)

Input Matrix:
[[7 7 8 4 9]
 [4 0 0 0 0]
 [6 0 2 1 8]
 [7 4 4 7 1]
 [2 2 6 2 1]]

Edge Detection Output:
[[11.  2. -7.]
 [15. -5. -9.]
 [ 6. -7.  5.]]

Blur Output:
[[3.77777778 2.44444444 3.55555556]
 [3.         2.         2.55555556]
 [3.66666667 3.11111111 3.55555556]]


5. Pick any Instagram photo, convert it to grayscale and a small NumPy array (e.g., 8x8), and use your convolution function to apply a custom filter of your choice. Show the input and output arrays and briefly describe what feature your filter detects.

In [6]:
from PIL import Image
import numpy as np

# Load Image
image = Image.open("virat_kohli.jpg")

# Convert to Grayscale
gray = image.convert("L")

# Resize to 8x8
gray = gray.resize((8,8))

# Convert to NumPy
matrix = np.array(gray)

print("Input Array:")
print(matrix)

# Sharpen Filter
kernel = np.array([
    [0,-1,0],
    [-1,5,-1],
    [0,-1,0]
])

output = np.zeros((6,6))

for i in range(6):
    for j in range(6):

        region = matrix[i:i+3,j:j+3]

        output[i,j] = np.sum(region * kernel)

print("\nOutput Array:")
print(output)

Input Array:
[[ 93  75  74  68  78  89  81  82]
 [ 82  93  95  93  94  92  96  90]
 [112 113 113 112 111 111 113 109]
 [105 103 102 103 108 113 101 101]
 [110 110 112 102  98 137 104 105]
 [119 117 113  57  33  89 112 108]
 [116 117 112  33  10  60 110  92]
 [108 110 114 100  94 102 108 111]]

Output Array:
[[ 100.  102.   96.   96.   70.  104.]
 [ 144.  143.  140.  130.  126.  148.]
 [  85.   79.   91.  115.  108.   74.]
 [ 108.  133.  140.  110.  281.   65.]
 [ 126.  167.    4.  -89.  103.  149.]
 [ 130.  183. -114. -170.  -11.  178.]]
