1. Create a Python script that loads a sample image (use any image of your favorite cricketer or celebrity), converts it to a NumPy array, and prints the array shape to demonstrate how images are represented for CNNs.



In [4]:
from PIL import Image
import numpy as np

# Load Image
image = Image.open("virat_kohli.jpg")

# Convert to NumPy Array
image_array = np.array(image)

# Print Shape
print("Image Shape:", image_array.shape)

Image Shape: (6000, 4000, 3)


2. Implement a simple 2D convolution operation in Python using NumPy: given a 5x5 grayscale image array and a 3x3 filter, compute the output feature map without using any deep learning libraries.<br><br><em><strong>Hint:</strong> Use nested loops to slide the filter over the image and sum the element-wise products.</em>

In [2]:
import numpy as np

# 5x5 Image
image = np.array([
    [1,2,3,0,1],
    [4,5,6,1,2],
    [7,8,9,2,3],
    [1,2,3,4,5],
    [6,7,8,9,0]
])

# 3x3 Filter
kernel = np.array([
    [1,0,-1],
    [1,0,-1],
    [1,0,-1]
])

# Output Size
output = np.zeros((3,3))

# Convolution
for i in range(3):
    for j in range(3):
        region = image[i:i+3, j:j+3]
        output[i,j] = np.sum(region * kernel)

print(output)

[[-6. 12. 12.]
 [-6.  8.  8.]
 [-6.  2. 12.]]


3. Draw the architecture diagram of a basic CNN (on paper or using a tool like draw.io) showing input layer, one convolutional layer, one pooling layer, and an output layer. Label each part and briefly describe its function in 1-2 lines.

- Input Layer: Accepts the input image as pixel values.
- Convolution Layer : Extracts important features such as edges, shapes, and textures using filters.
- Pooling Layer : Reduces the feature map size while keeping the most important information.
- output layer : Uses extracted features to predict the final class or output.

4. Write a function in Python that takes an image array and returns a new array where each pixel is replaced by the maximum value in its 2x2 local neighborhood (simulate max pooling).<br><br><em><strong>Constraint:</strong> Do not use any deep learning libraries like TensorFlow or PyTorch for this task.</em>

In [3]:
import numpy as np

def max_pooling(image):

    rows, cols = image.shape

    output = np.zeros((rows//2, cols//2))

    for i in range(0, rows, 2):
        for j in range(0, cols, 2):

            block = image[i:i+2, j:j+2]

            output[i//2, j//2] = np.max(block)

    return output


# Example
image = np.array([
    [1,3,2,4],
    [5,6,7,8],
    [2,4,6,8],
    [1,3,5,7]
])

result = max_pooling(image)

print(result)

[[6. 8.]
 [4. 8.]]


5. Explain with a real-world example from Instagram or Zomato how translation invariance in CNNs is useful. Write 2-3 sentences connecting it to how these apps recognize faces or food items even if they appear in different positions in the image.

#### Answer:

- Instagram: CNNs can recognize a person's face even if it appears in the top, bottom, or side of a photo. This property, called translation invariance, helps Instagram tag people accurately regardless of where the face is located in the image.

- Zomato: CNNs can identify food items such as pizza or burgers even if they appear in different positions or angles in a photo. This allows the app to recognize dishes consistently despite changes in image composition.