1. Prepare a sequence dataset from Flipkart product prices over 10 days (you can create fake data) and reshape it into the format required for LSTM input using NumPy.

In [1]:
import numpy as np

# Fake Flipkart product prices (10 days)
prices = np.array([45000, 45200, 45150, 45500, 45800,
                   46000, 46250, 46500, 46700, 47000])

# Create sequences
X = []
y = []

sequence_length = 3

for i in range(len(prices) - sequence_length):
    X.append(prices[i:i + sequence_length])
    y.append(prices[i + sequence_length])

# Convert to NumPy arrays
X = np.array(X)
y = np.array(y)

# Reshape for LSTM
X = X.reshape((X.shape[0], X.shape[1], 1))

print("Input Shape:", X.shape)
print("Target Shape:", y.shape)

print("\nInput Sequences:")
print(X)

print("\nTarget Values:")
print(y)

Input Shape: (7, 3, 1)
Target Shape: (7,)

Input Sequences:
[[[45000]
  [45200]
  [45150]]

 [[45200]
  [45150]
  [45500]]

 [[45150]
  [45500]
  [45800]]

 [[45500]
  [45800]
  [46000]]

 [[45800]
  [46000]
  [46250]]

 [[46000]
  [46250]
  [46500]]

 [[46250]
  [46500]
  [46700]]]

Target Values:
[45500 45800 46000 46250 46500 46700 47000]


2. Build a simple LSTM model in Keras to predict the next value in your prepared Flipkart price sequence and train it for 10 epochs.

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

# Build LSTM Model
model = Sequential([
    LSTM(32, input_shape=(3,1)),
    Dense(1)
])

# Compile
model.compile(
    optimizer='adam',
    loss='mse'
)

# Train
model.fit(
    X,
    y,
    epochs=10,
    verbose=1
)

Epoch 1/10


c:\Users\tejal\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - loss: 2139333376.0000
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - loss: 2139332608.0000
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - loss: 2139331712.0000
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 2139331200.0000
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 2139330304.0000
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: 2139329920.0000
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 2139329408.0000
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 2139328512.0000
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2139327872.0000
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 2139327104.0000


3. Evaluate your trained LSTM model by predicting the next price in the sequence, and print both the predicted and actual values for comparison.<br><br><em><strong>Hint:</strong> Use model.predict() and compare with the last actual value in your test set.</em>

In [3]:
# Predict
prediction = model.predict(X)

print("Predicted Price:", prediction[-1][0])
print("Actual Price   :", y[-1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 133ms/step
Predicted Price: -0.299206
Actual Price   : 47000


4. Write a short code snippet to switch your LSTM layer to a GRU layer in the same model and retrain it. Compare the training time and prediction result with your LSTM model.<br><br><em><strong>Hint:</strong> Replace keras.layers.LSTM with keras.layers.GRU and keep other parameters the same.</em>

In [4]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense
import time

# Build GRU Model
gru_model = Sequential([
    GRU(32, input_shape=(3,1)),
    Dense(1)
])

gru_model.compile(
    optimizer='adam',
    loss='mse'
)

# Measure Training Time
start = time.time()

gru_model.fit(
    X,
    y,
    epochs=10,
    verbose=1
)

end = time.time()

print("Training Time:", end - start, "seconds")

# Prediction
prediction = gru_model.predict(X)

print("Predicted Price:", prediction[-1][0])

Epoch 1/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 5s 5s/step - loss: 2139260672.0000
Epoch 2/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 2139259136.0000
Epoch 3/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 2139257472.0000
Epoch 4/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 2139255936.0000
Epoch 5/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 2139254016.0000
Epoch 6/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 2139252480.0000
Epoch 7/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 2139250816.0000
Epoch 8/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - loss: 2139248896.0000
Epoch 9/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 2139247616.0000
Epoch 10/10
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 2139245824.0000
Training Time: 5.446825265884399 seconds
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step
Predicted Price: 0.59233975


5. Use ChatGPT to generate a Python function that prepares any sequence data (such as daily Spotify song play counts) for LSTM input, and explain in your own words how the function works.

In [5]:
import numpy as np

def prepare_sequence(data, sequence_length):

    X = []
    y = []

    for i in range(len(data) - sequence_length):
        X.append(data[i:i + sequence_length])
        y.append(data[i + sequence_length])

    X = np.array(X)
    y = np.array(y)

    X = X.reshape((X.shape[0], X.shape[1], 1))

    return X, y


# Example
spotify_plays = [120, 150, 180, 200, 210, 230, 250]

X, y = prepare_sequence(spotify_plays, 3)

print("Input Shape:", X.shape)
print("Target:", y)

Input Shape: (4, 3, 1)
Target: [200 210 230 250]
