1. Create a 6x6 NumPy array with random integers (0-255) to simulate a grayscale image, then apply a 2x2 max pooling operation with a stride of 2 and print the resulting reduced array.

In [1]:
import numpy as np

# Create 6x6 random grayscale image
image = np.random.randint(0, 256, (6, 6))

print("Original Image:")
print(image)

# Max Pooling (2x2, stride=2)
output = np.zeros((3, 3), dtype=int)

for i in range(0, 6, 2):
    for j in range(0, 6, 2):
        output[i//2, j//2] = np.max(image[i:i+2, j:j+2])

print("\nMax Pooled Image:")
print(output)

Original Image:
[[115 201 124  32  43  56]
 [ 84 155 249 136 102  20]
 [177  20 132 178 224 231]
 [174  65 207 135  56  88]
 [230  20 188 189 143 208]
 [ 56 206 152 166  40  32]]

Max Pooled Image:
[[201 249 102]
 [177 207 231]
 [230 189 208]]


2. Write a Python function average_pooling_2x2(image) that takes a 2D NumPy array and returns a new array after applying 2x2 average pooling with stride 2.

In [2]:
import numpy as np

def average_pooling_2x2(image):

    rows, cols = image.shape

    output = np.zeros((rows//2, cols//2))

    for i in range(0, rows, 2):
        for j in range(0, cols, 2):

            block = image[i:i+2, j:j+2]
            output[i//2, j//2] = np.mean(block)

    return output


# Example
image = np.array([
    [2,4,6,8],
    [1,3,5,7],
    [8,6,4,2],
    [7,5,3,1]
])

print(average_pooling_2x2(image))

[[2.5 6.5]
 [6.5 2.5]]


3. Given a 4x4 feature map array, manually perform both max pooling and average pooling with a 2x2 window and stride 2, and compare the results side by side.<br><br><em><strong>Hint:</strong> Show both resulting arrays and explain in one line which pooling method keeps more details from the original image.</em>

In [3]:
import numpy as np

feature_map = np.array([
    [1,3,2,4],
    [5,6,7,8],
    [2,4,6,8],
    [1,3,5,7]
])

# Max Pooling
max_pool = np.array([
    [6,8],
    [4,8]
])

# Average Pooling
avg_pool = np.array([
    [(1+3+5+6)/4, (2+4+7+8)/4],
    [(2+4+1+3)/4, (6+8+5+7)/4]
])

print("Original Feature Map:")
print(feature_map)

print("\nMax Pooling:")
print(max_pool)

print("\nAverage Pooling:")
print(avg_pool)

Original Feature Map:
[[1 3 2 4]
 [5 6 7 8]
 [2 4 6 8]
 [1 3 5 7]]

Max Pooling:
[[6 8]
 [4 8]]

Average Pooling:
[[3.75 5.25]
 [2.5  6.5 ]]


4. Combine a single 3x3 convolution layer (use any simple filter, e.g., edge detection) followed by a 2x2 max pooling layer on a 5x5 input array. Show the output after each step.

In [4]:
import numpy as np

# Input Image
image = np.array([
    [1,2,3,4,5],
    [5,6,7,8,9],
    [9,8,7,6,5],
    [5,4,3,2,1],
    [1,2,3,4,5]
])

# Edge Detection Filter
kernel = np.array([
    [1,0,-1],
    [1,0,-1],
    [1,0,-1]
])

# Convolution
conv_output = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        region = image[i:i+3, j:j+3]
        conv_output[i,j] = np.sum(region * kernel)

print("Convolution Output:")
print(conv_output)

# Max Pooling
pool_output = np.zeros((1,1))

pool_output[0,0] = np.max(conv_output[0:2,0:2])

print("\nMax Pooling Output:")
print(pool_output)

Convolution Output:
[[-2. -2. -2.]
 [ 2.  2.  2.]
 [ 2.  2.  2.]]

Max Pooling Output:
[[2.]]


5. Explain in your own words, using an example from Instagram or Zomato, how pooling layers help reduce computation and improve feature extraction in deep learning models.

#### Answer:

- Instagram: When Instagram recognizes a person's face, pooling layers reduce the size of the feature maps while preserving important facial features like the eyes, nose, and mouth. This speeds up processing and helps the model recognize faces even if they appear at different positions or scales.

- Zomato: When Zomato identifies food items from images, pooling layers retain the most important visual features, such as the shape or texture of the food, while reducing unnecessary details. This decreases computation and allows the model to recognize dishes more efficiently.