#### 1. Create two NumPy arrays representing the daily step counts of two friends over a week and use element-wise addition, subtraction, multiplication, and division to compare their activity levels.

In [1]:
import numpy as np

friend1 = np.array([6500, 7200, 8000, 9000, 7500, 10000, 8500])
friend2 = np.array([6000, 7000, 7800, 9500, 7300, 9800, 8200])

addition = friend1 + friend2

subtraction = friend1 - friend2

multiplication = friend1 * friend2

division = friend1 / friend2

print("Friend 1 Steps:", friend1)
print("Friend 2 Steps:", friend2)

print("\nElement-wise Addition:")
print(addition)

print("\nElement-wise Subtraction:")
print(subtraction)

print("\nElement-wise Multiplication:")
print(multiplication)

print("\nElement-wise Division:")
print(division)

Friend 1 Steps: [ 6500  7200  8000  9000  7500 10000  8500]
Friend 2 Steps: [6000 7000 7800 9500 7300 9800 8200]

Element-wise Addition:
[12500 14200 15800 18500 14800 19800 16700]

Element-wise Subtraction:
[ 500  200  200 -500  200  200  300]

Element-wise Multiplication:
[39000000 50400000 62400000 85500000 54750000 98000000 69700000]

Element-wise Division:
[1.08333333 1.02857143 1.02564103 0.94736842 1.02739726 1.02040816
 1.03658537]


#### 2.Simulate a Spotify-like 'Recommended Songs' feature: Given two 3x3 matrices representing user-song interaction scores (user preferences and song popularity), use dot() and matmul() to compute the final recommendation matrix and explain the difference between the two results.

In [2]:
import numpy as np
user_preferences = np.array([
    [5, 3, 2],
    [4, 1, 5],
    [2, 4, 3]
])

song_popularity = np.array([
    [10, 20, 30],
    [15, 25, 35],
    [20, 30, 40]
])

recommendation_dot = np.dot(user_preferences, song_popularity)

recommendation_matmul = np.matmul(user_preferences, song_popularity)

print("User Preference Matrix:")
print(user_preferences)

print("\nSong Popularity Matrix:")
print(song_popularity)

print("\nRecommendation Matrix using dot():")
print(recommendation_dot)

print("\nRecommendation Matrix using matmul():")
print(recommendation_matmul)

User Preference Matrix:
[[5 3 2]
 [4 1 5]
 [2 4 3]]

Song Popularity Matrix:
[[10 20 30]
 [15 25 35]
 [20 30 40]]

Recommendation Matrix using dot():
[[135 235 335]
 [155 255 355]
 [140 230 320]]

Recommendation Matrix using matmul():
[[135 235 335]
 [155 255 355]
 [140 230 320]]


#### 3.Given a 4x4 NumPy matrix representing the pixel brightness of a small Instagram image, use transpose (T) to rotate the image and then calculate the mean, median, standard deviation, and variance of the pixel values

In [3]:
import numpy as np

image = np.array([
    [120, 150, 180, 200],
    [100, 130, 170, 210],
    [90, 140, 160, 220],
    [80, 110, 190, 230]
])

rotated_image = image.T

mean_value = np.mean(image)
median_value = np.median(image)
std_value = np.std(image)
variance_value = np.var(image)

print("Original Image:")
print(image)

print("\nTransposed Image:")
print(rotated_image)

print("\nMean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_value)
print("Variance:", variance_value)

Original Image:
[[120 150 180 200]
 [100 130 170 210]
 [ 90 140 160 220]
 [ 80 110 190 230]]

Transposed Image:
[[120 100  90  80]
 [150 130 140 110]
 [180 170 160 190]
 [200 210 220 230]]

Mean: 155.0
Median: 155.0
Standard Deviation: 46.09772228646444
Variance: 2125.0


#### 4.Take a 3x3 NumPy matrix representing a Zomato restaurant rating correlation grid and use np.linalg.inv(), np.linalg.det(), and np.linalg.eig() to compute its inverse, determinant, and eigenvalues/eigenvectors.<br><br><em><strong>Hint:</strong> If the matrix is not invertible, modify one value and try again.</em>

In [4]:
import numpy as np

ratings = np.array([
    [4, 2, 1],
    [1, 3, 2],
    [2, 1, 5]
])

determinant = np.linalg.det(ratings)

inverse = np.linalg.inv(ratings)

eigenvalues, eigenvectors = np.linalg.eig(ratings)

print("Original Matrix:")
print(ratings)

print("\nDeterminant:")
print(determinant)

print("\nInverse Matrix:")
print(inverse)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

Original Matrix:
[[4 2 1]
 [1 3 2]
 [2 1 5]]

Determinant:
45.000000000000014

Inverse Matrix:
[[ 0.28888889 -0.2         0.02222222]
 [-0.02222222  0.4        -0.15555556]
 [-0.11111111  0.          0.22222222]]

Eigenvalues:
[7.14092334+0.j         2.42953833+0.63170371j 2.42953833-0.63170371j]

Eigenvectors:
[[ 0.52501432+0.j          0.7363341 +0.j          0.7363341 -0.j        ]
 [ 0.46961182+0.j         -0.39625542+0.34424633j -0.39625542-0.34424633j]
 [ 0.7098061 +0.j         -0.36387363-0.22334768j -0.36387363+0.22334768j]]


#### 5.Create a NumPy array of shape (2, 6) representing the number of orders placed on Swiggy in two cities over 6 days. Reshape it to (3, 4), flatten it, split it into two equal parts, and then stack both parts vertically.

In [5]:
import numpy as np

orders = np.array([
    [120, 135, 150, 140, 160, 170],  # City 1
    [110, 125, 145, 155, 165, 180]   # City 2
])

print("Original Array (2x6):")
print(orders)


reshaped_orders = orders.reshape(3, 4)

print("\nReshaped Array (3x4):")
print(reshaped_orders)

flattened_orders = reshaped_orders.flatten()

print("\nFlattened Array:")
print(flattened_orders)

split_orders = np.split(flattened_orders, 2)

print("\nFirst Part:")
print(split_orders[0])

print("\nSecond Part:")
print(split_orders[1])

stacked_orders = np.vstack(split_orders)

print("\nVertically Stacked Array:")
print(stacked_orders)

Original Array (2x6):
[[120 135 150 140 160 170]
 [110 125 145 155 165 180]]

Reshaped Array (3x4):
[[120 135 150 140]
 [160 170 110 125]
 [145 155 165 180]]

Flattened Array:
[120 135 150 140 160 170 110 125 145 155 165 180]

First Part:
[120 135 150 140 160 170]

Second Part:
[110 125 145 155 165 180]

Vertically Stacked Array:
[[120 135 150 140 160 170]
 [110 125 145 155 165 180]]
