#### 1.Create a 2D NumPy array representing the ratings (out of 5) given by 4 users to 5 different food items on Zomato. Use slicing to extract the ratings given by the second and third users only.

In [1]:
import numpy as np

ratings = np.array([
    [5, 4, 3, 5, 4],  
    [4, 5, 4, 3, 5],  
    [3, 4, 5, 4, 4],  
    [5, 5, 4, 5, 3]   
])


print("Ratings Matrix:")
print(ratings)

selected_users = ratings[1:3]

print("\nRatings of Second and Third Users:")
print(selected_users)

Ratings Matrix:
[[5 4 3 5 4]
 [4 5 4 3 5]
 [3 4 5 4 4]
 [5 5 4 5 3]]

Ratings of Second and Third Users:
[[4 5 4 3 5]
 [3 4 5 4 4]]


#### 2.Given a NumPy array of daily steps tracked for 10 days, use boolean indexing to select only the days where the steps were greater than 8000.<br><br><em><strong>Hint:</strong> Use an array like steps = np.array([7500, 8200, 9000, ...]) and apply a boolean condition.</em>

In [2]:
import numpy as np

steps = np.array([7500, 8200, 9000, 6800, 10000, 7900, 8500, 9200, 7600, 11000])

high_steps = steps[steps > 8000]

print("Daily Steps:")
print(steps)

print("\nDays with more than 8000 steps:")
print(high_steps)

Daily Steps:
[ 7500  8200  9000  6800 10000  7900  8500  9200  7600 11000]

Days with more than 8000 steps:
[ 8200  9000 10000  8500  9200 11000]


#### 3.Create a NumPy array of IPL team scores for 8 matches. Use fancy indexing to select the scores from matches 2, 5, and 7, and print them.

In [3]:
import numpy as np

scores = np.array([180, 195, 165, 210, 175, 190, 205, 185])

selected_scores = scores[[1, 4, 6]]

print("IPL Team Scores:")
print(scores)

print("\nScores from Match 2, Match 5, and Match 7:")
print(selected_scores)

IPL Team Scores:
[180 195 165 210 175 190 205 185]

Scores from Match 2, Match 5, and Match 7:
[195 175 205]


#### 4.Suppose you have a NumPy array of product prices from Flipkart. Use broadcasting to apply a 10% discount to all prices and print the new array.<br><br><em><strong>Constraint:</strong> Do not use any loops.</em>

In [4]:
import numpy as np

prices = np.array([500, 1200, 750, 2500, 999])

discounted_prices = prices * 0.90

print("Original Prices:")
print(prices)

print("\nPrices after 10% Discount:")
print(discounted_prices)

Original Prices:
[ 500 1200  750 2500  999]

Prices after 10% Discount:
[ 450.  1080.   675.  2250.   899.1]


#### 5.Given a NumPy array of user ratings (can be negative, zero, or positive) for songs on Spotify, use boolean masking to set all negative ratings to zero, keeping other ratings unchanged.

In [5]:
import numpy as np

ratings = np.array([5, -2, 3, 0, -1, 4, -5, 2])

ratings[ratings < 0] = 0

print("Updated Ratings:")
print(ratings)

Updated Ratings:
[5 0 3 0 0 4 0 2]
